diploiTemplateVersion: V1.0
name: telegram-bot
description: Telegram Bot on Diploi
defaultName: Telegram Bot

stages:
  - name: Development
    identifier: development
    disableConfirmation: true
  - name: Staging
    identifier: staging
    disableConfirmation: true
  - name: Production
    identifier: production
    disableConfirmation: true

contexts:
  - name: app
    identifier: app

environmentVariables:
  - identifier: TG_BOT_API_KEY
    defaultValue: xxx
    type: secret
    contexts: label=app
  - identifier: OPENAI_API_KEY
    defaultValue: xxx
    type: secret
    contexts: label=app

repositories:
  - name: app
    identifier: app

hosts:
  - name: App
    identifier: app
    urlFormat: '[label].[default-domain]'

ssh:
  - usernameFormat: '[label]'
    contexts: label=app
    stages:
      - development
  - usernameFormat: '[label]-[index]'
    contexts: label=app
    stages:
      - production
  - usernameFormat: '[label]'
    contexts: label=app
    stages:
      - staging
logs:
  - identifier: tgbot-log
    name: TGBOT Log
    labelSelector: app=app
    command: tail -n 2000 -F /var/log/tgbot.log

images:
  - identifier: app
    repository: app
    dockerfile: Dockerfile
    image: ghcr.io/filbe/diploi-tgbot-template
    initialProjectImage: ghcr.io/filbe/diploi-tgbot-template
    stages:
      - development
      - production
      - staging
    manualBuildStages:
      - development

storage:
  - identifier: app
    stages:
      - development
    sizeMiB: 1000

status:
  url: http://app:3000/status
